worker_processes  1;

events {
  worker_connections  1024;
}

http {

  upstream grpc_backends {
    server server1:50051;
    server server2:50051;
    server server3:50051;
  }

  server {
    listen 8080 http2;

    location / {
      grpc_pass grpc://grpc_backends;


      grpc_set_header Host $host;
      grpc_set_header X-Real-IP $remote_addr;


      grpc_read_timeout 3600s;
      grpc_send_timeout 3600s;
    }
  }
}
